PUT http://localhost:3001/animal/628d4e676a6e08fd2ddfd9ab
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGQwOTQ4MTk4YmQ4ODM2NzJjMzFhZiIsIm1haWwiOiJqdWFuQGdtYWlsLmNvbSIsImlhdCI6MTY1MzQyMzQ3OX0.oZ70AA9Vm_1S2FvXOclfLfMLem00c9UyMuuUICNjt4A

{
    "type": "Cat",
    "gender": "Female",
    "age": "2 years",
    "size": "Medium",
    "description": "My name is Vacco and I am a neutered female. My rescuer thinks I am about 2 years old.",
    "temporaryName": "Vacco",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTst-ZhrNnLykIfO77sofsbnDd-CuQsEV8xzw&usqp=CAU",
    "location": "-38.94979895445034 -68.04452851658687"
}