export const inputArray = [
  {
    name: "name",
    type: "text",
    placeholder: "First Name",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "lastname",
    type: "text",
    placeholder: "Last Name",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "mail",
    type: "email",
    placeholder: "Mail",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "password",
    type: "password",
    placeholder: "Password",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "location",
    type: "text",
    placeholder: "Location",
    value: "",
    error: false,
    errorMessage: "",
  },
];

export const loginArray = [
  {
    name: "mail",
    type: "email",
    placeholder: "Mail",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "password",
    type: "password",
    placeholder: "Password",
    value: "",
    error: false,
    errorMessage: "",
  },
];

export const createRescueAnimal = [
  {
    name: "temporaryName",
    type: "text",
    placeholder: "Temporary Name",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "type",
    type: "text",
    placeholder: "Type",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "gender",
    type: "text",
    placeholder: "Gender",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "age",
    type: "text",
    placeholder: "Age",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "size",
    type: "text",
    placeholder: "Size",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "description",
    type: "text",
    placeholder: "Description",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "location",
    type: "text",
    placeholder: "Location",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "image",
    type: "file",
    placeholder: "Image",
    value: "",
    error: false,
    errorMessage: "",
  },
];

export const edituser = [
  {
    name: "name",
    type: "text",
    placeholder: "First Name",
    enableButton: true,
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "lastname",
    type: "text",
    placeholder: "Last Name",
    enableButton: true,
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "mail",
    type: "email",
    placeholder: "Mail",
    enableButton: true,
    value: "",
    error: false,
    errorMessage: "",
  },
];

export const changepassword = [
  {
    name: "oldPassword",
    type: "password",
    placeholder: "Old Password",
    value: "",
    error: false,
    errorMessage: "",
  },
  {
    name: "newPassword",
    type: "password",
    placeholder: "New Password",
    value: "",
    error: false,
    errorMessage: "",
  },
];
