POST http://localhost:3001/adopt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGQwOWU4MTk4YmQ4ODM2NzJjMzFiOSIsIm1haWwiOiJwYXVAZ21haWwuY29tIiwiaWF0IjoxNjUzNDI5NzgyfQ.YnxqLIRRBWPZBn3q1iNw3td72O1sU8wSq9SmYkSf9Zw

{
    "date": "24-05-2022",
    "adoptionCode": "1234",
    "rescuer": "628d0948198bd883672c31af",
    "animal": "628d51b7f52ca82d6682ad71"
}