PUT http://localhost:3001/favorite/628d6a83ae8bbf6cb6772412
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGQwOTQ4MTk4YmQ4ODM2NzJjMzFhZiIsIm1haWwiOiJqdWFuQGdtYWlsLmNvbSIsImlhdCI6MTY1MzQyMzQ3OX0.oZ70AA9Vm_1S2FvXOclfLfMLem00c9UyMuuUICNjt4A