GET https://foster-pet.herokuapp.com/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGZhN2U3OTU4OTQzZThmODA0NjcwOCIsIm1haWwiOiJ0aWFnb0BnbWFpbC5jb20iLCJpYXQiOjE2NTM2MDI5NzJ9.tliGcErxgXoImCmoxbsqLO3gqWxQRr7NmR91Rw3QxbU