DELETE  http://localhost:3001/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGQ0OTA0MjA3NGRkNDEwNjMzZTI0OSIsIm1haWwiOiJ0aWFnb0BnbWFpbC5jb20iLCJpYXQiOjE2NTM0MjcyMTV9.D_shX91WNJe0MrCzdYhLJmHvpERaDNFFeQzWynEPXeU