PUT http://localhost:3001/user/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOGMxNmY3NTdjZTZkZTUyYTdjZjMyYyIsIm1haWwiOiJqdWFuQGdtYWlsLmNvbSIsImlhdCI6MTY1MzM0ODEwMH0.Vy_ORZspvG5L4HgUsMe3h5Bxe9wmo0dUNDnExZq3_t8

{
    "oldPassword": "Hola1234",
    "newPassword": "Hola12345"
}